### ISSUE TITLE
Support for multiple builds and release artefacts when releasing

### ISSUE THREAD

**Issue by tomyan** [mergermarket/cdflow2#2]
Currently there is a single release image that is used to create the release. However, at least two teams want to produce multiple release artefacts - e.g. a docker image for use with ECS and a lambda zip.

My current thinking is that `cdflow.yaml` would contain the following to configure the release:

```yaml
release:
  - image: bulid-and-publish-docker-image:latest
  - image: build-and-publish-lambda-zip:latest
    tfvar: lambdarelease
```

The `tfvar` key would correspond to terraform dictionary variable that the release metadata would be provided in. These would be enforced unique with the default being `release` (where the global release metadata - i.e. version, component, commit & team - would also be added).

Another option might be to use the terraform variable name as a key - e.g.

```yaml
build:
  docker: bulid-and-publish-docker-image:latest
  lambda: build-and-publish-lambda-zip:latest
```

This has the advantage of naturally ensuring the variable names are unique, and probably implies separating the concern of the global release metadata (I guess still in a `release` map).

Both formats would leave room if you wanted further customisation in the future. With the second version you could replace the value with a map where the image is a key (similar to how docker build works in a docker compose file)

**Comment by tomyan** [comment]
Initial implementation for this in place following second - the following are equivalent and result in release metadata in a `release` terraform map variable:

```yaml
release: release-image
```

```yaml
release:
  release: release-image
```

```yaml
release:
  release:
    image: release-image
```

Two builds would be achieved with:

```yaml
release:
  docker: docker-release-image
  lambda: lambda-release-image
```

...or equivalently:

```yaml
release:
  docker:
    image: docker-release-image
  lambda:
    image: lambda-release-image
```

These would result in `docker` and `lambda` terraform map variables being passed. The built-in keys (`component`, `version`, `commit` and `team`) are added to each map. These are also always provided via a `release` map regardless of whether there is a `release` key (so these builtins can be accessed there consistently).

In the current implementation the builds are run in serial, but it would be a good future enhancement to run then in parallel.
